### ISSUE TITLE
How to host blog at domain.com/blog/article?

### ISSUE THREAD

**Issue by ajmalafif** [DSchau/gatsby-blog-starter-kit#28]
Hi, 

This is easily one of the most useful articles and resources on how to practically use GatsbyJS. Thank you so much for sharing this. 

I was trying out how to host the `www.domain.com/blog` but still have other pages like `www.domain.com/about` and landing page in tact.

I tried changing the PathPrefix in `gatsby-config.js` but that's not working. Any help or guidance is greatly appreciated!

**Comment by DSchau** [comment]
Sure! So since it's static content and you have an existing domain, this should be pretty easy.

Let's say you have an S3 bucket, and your structure is:

```
index.html
about/
  index.html
```

which will give you the structure you specified. To get your blog hosted at `/blog` you simply need to use the pathPrefix option in gatsby-config.js, e.g.

```js
module.exports = {
  // Note: it must *not* have a trailing slash.
  pathPrefix: `/blog`,
};
```

and then change the `build` script in `package.json` to `gatsby build --prefix-paths` and run the `yarn build` or `npm run build`

Then, simply grab the contents of the public folder, create a `blog` folder (on your S3 bucket or wherever) and drag the contents of public _into_ that folder.

So that should work! For the record, I like using CNAME to redirect, e.g. my blog is hosted at https://blog.dustinschau.com instead of a folder at https://dustinschau.com/blog!

**Comment by ajmalafif** [comment]
Hi thanks for the reply! 

I am sorry for not being clear. I think it's clearer with a real example URL: https://learn-gatsby-blog.netlify.com/

So for now I managed to learn from your article and created a third post which is here https://learn-gatsby-blog.netlify.com/third-blog

I think what I am asking is if I could have that article inside https://learn-gatsby-blog.netlify.com/blog/third-blog and https://learn-gatsby-blog.netlify.com/blog has the listing of all the articles. 

So I can have https://learn-gatsby-blog.netlify.com/ as a homepage and https://learn-gatsby-blog.netlify.com/about as about page, and as you can imagine for contact and so on.

Hope that is clearer! Apologies for earlier confusion 😭

**Comment by DSchau** [comment]
Sure!

So I think you just need to change [this file](https://github.com/DSchau/gatsby-blog-starter-kit/blob/master/src/pages/index.js) to blog.js, and then add whatever content you want to index.js!

**Comment by ajmalafif** [comment]
Oh wow that makes perfect sense! Thank you so much!

**Comment by DSchau** [comment]
Of course!
